<?php
/**
 * Webkul Software.
 *
 * @category  Webkul
 * @package   Webkul_Marketplace
 * @author    Webkul Software Private Limited
 * @copyright Webkul Software Private Limited (https://webkul.com)
 * @license   https://store.webkul.com/license.html
 */
$product = $block->getProduct();
$fulfilmentImage = $block->getFulfilmentImage($product);
$fulfilmentImage = $fulfilmentImage??$block->getViewFileUrl('Webkul_Marketplace::images/avatar/fulfilmentImage.png');
$fulfilmentText = $block->getFulfilmentText($product);
$fulfillmentStatus = $block->getConfigValue("general_settings", "fulfillment_status");
if ($fulfillmentStatus) {
    ?>
<div class="wk-seller-card-row">
    <img src="<?= $escaper->escapeUrl($fulfilmentImage); ?>">
    <div><?= $escaper->escapeHtml($fulfilmentText); ?></div>
</div>
    <?php
}
?>